-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.departemen
(
    id_dep serial NOT NULL,
    nama_departemen character varying(50) NOT NULL,
    PRIMARY KEY (id_dep)
);

CREATE TABLE IF NOT EXISTS public.jabatan
(
    id_jabatan serial NOT NULL,
    nama_jabatan character varying(50) NOT NULL,
    salary numeric(12, 2) NOT NULL,
    PRIMARY KEY (id_jabatan)
);

CREATE TABLE IF NOT EXISTS public.karyawan
(
    id_karyawan serial NOT NULL,
    nama_karyawan character varying(50) NOT NULL,
    id_dep integer NOT NULL,
    id_jabatan integer NOT NULL,
    PRIMARY KEY (id_karyawan)
);

ALTER TABLE IF EXISTS public.karyawan
    ADD CONSTRAINT "Departemen" FOREIGN KEY (id_dep)
    REFERENCES public.departemen (id_dep) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.karyawan
    ADD CONSTRAINT "Jabatan" FOREIGN KEY (id_jabatan)
    REFERENCES public.jabatan (id_jabatan) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;